@startuml
title Create flow step

#BDB5D5:Client sends a POST request to /flows/{flow_id}/steps;
-> calls;
#ADD1B2:FlowService;
while (add_step)
    #ADD1B2:WidgetGateway;
    :create;
    note right
        Client sends a POST request based on Widget type
    end note
    if (Screen, Rule,\nIntegartion and\nReport service) then (status code 201);
        #ADD1B2:Step;
    else (status code 400-404)
    #EB937F:If there is an error raise the exception:\n\nWidgetCreationFailedException;
    kill
    endif
-> return step object;
endwhile
-> call after step;
#ADD1B2:Flow;
:add_step;
#ADD1B2:FlowRepository;
:save;
floating note:StepCreated
split
    #ADD1B2:Flow;
split again
    #ADD1B2:Event(s);
end split
#F2D2BD:Firestore;
-> triggers;
#A7C7E7:Publisher;
legend right
    Legend
    | method |
    |<#ADD1B2> class |
    |<#EB937F> error |
    |<#F2D2BD> database |
    |<#BDB5D5> process |
    |<#A7C7E7> publisher |
endlegend
@enduml
