@startuml
title Delete Flow Step

#BDB5D5:Client sends a DELETE request to /flows/{flow_id}/steps/{step_id};
-> calls;
#ADD1B2:FlowService;
floating note: Responses:\n{'message': 'Step successfully deleted'}, 200 or\n{'message': 'Flow step not found'}, 404
:delete_step;
floating note right
    Raise the exception:
    AggregateNotFoundException
end note
#ADD1B2:Flow;
:delete_step;
floating note right
    Raise the exception:
    StepNotFoundException
end note
floating note: Events:\nStepRemoved\nStepConnectionRemoved
#ADD1B2:Step;
:remove_connection;
#ADD1B2:FlowRepository;
:save;
split
    #ADD1B2:Flow;
split again
    #ADD1B2:Event(s);
end split
#F2D2BD:Firestore;
-> triggers;
#A7C7E7:Publisher;
legend right
    Legend
    | method |
    |<#ADD1B2> class |
    |<#EB937F> error |
    |<#F2D2BD> database |
    |<#BDB5D5> process |
    |<#A7C7E7> publisher |
endlegend
@enduml