@startuml
title Fetch flows

#B4A7E5:Client sends a GET request to /flows;
-> calls;
#ADD1B2:FlowService;
:list;
#ADD1B2:FlowRepository;
:find_flow_by_company_and_app_ids;
legend right
    Legend
    | method |
    |<#ADD1B2> class |
    |<#BDB5D5> process |
endlegend
@enduml
