@startuml
title Recover Flow from recycle bin
repeat: Client sends a PUT request to /flows/{flow_id}/recovers;
    -> calls;
    #ADD1B2:FlowService;
    floating note: If flow restored -> response:\n{'message': 'Flow successfully recovered'}, 200
    floating note: If raise error -> response:\n{'message': 'Flow not found'}, 404
repeat while (recover) -> Flow info

floating note right
    Raise the exception:
    AggregateNotFoundException
end note
#ADD1B2:Flow;
:recover;
note left
    Event:
    FlowRestored
end note
#ADD1B2:FlowRepository;
:save;
split
    #ADD1B2:Flow;
split again
    #ADD1B2:Event(s);
end split
#F2D2BD:Firestore;
-> triggers;
#A7C7E7:Publisher;
legend right
    Legend
    | method |
    |<#ADD1B2> class |
    |<#EB937F> error |
    |<#F2D2BD> database |
    |<#BDB5D5> process |
    |<#A7C7E7> publisher |
endlegend
@enduml