@startuml

' This block will be included in all versions of the diagram

version v1
' This block will only be included in the v1 version of the diagram

version v2
' This block will only be included in the v2 version of the diagram

@enduml
