@startuml
title Update a Rule

#BDB5D5:Client sends a PATCH request to:\n /rules/<rule_id>;
-> calls;
#ADD1B2:RuleService;
if (update) then ({response: rule_object}, 200\n yes)
   #ADD1B2:RuleRepository;
    :save;
    floating note:One of these events will be emitted\nbased on the update:\n\nRuleNameUpdated\nRuleInfoUpdated
    split
        #ADD1B2:Rule;
    split again
        #ADD1B2:Events/Event;
    end split
    #F2D2BD:Firestore;
    -> triggers;
    #A7C7E7:Publisher;
    kill
else ({'message': 'Rule object not found'}, 404\n no)
    #EB937F:If there is an error, then raise the exception:\nAggregateNotFoundException;
    kill
endif

legend right
    Legend
    | method |
    |<#ADD1B2> class |
    |<#F2D2BD> database |
    |<#BDB5D5> process |
    |<#A7C7E7> publisher |
endlegend
@enduml
