@startuml
title Rakizo builder image

skinparam activity {
  BackgroundColor #A7C7E7
}

#BDB5D5:Pull image;
:Cloud SDK;
#BDB5D5:Install apt package\nCopy build scripts;
#BDB5D5:Push image;
repeat:Container Registry;
#BDB5D5:Pull base image;
floating note #E6E6FA:Add to the image\n\nJava layer\nPython layer\nFlutter layer\nDocs layer
backward:Push image;
legend right
    Legend
    |<#BDB5D5> process |
    |<#A7C7E7> cloud service |
endlegend
@enduml