@startuml
title Release process

skinparam activity {
  BackgroundColor #A7C7E7
}

#BDB5D5:Commit to master branch or tag version;
repeat:Bitbucket;
:Cloud Source Repositories;
floating note #E6E6FA:Code mirrored from Bitbucket
-> triggers;
:Cloud Build;
#BDB5D5:Start deployment;
floating note #E6E6FA:Libraries\n\nStep 1\nInstall dependencies\n\nStep 2\nDocument\n\nStep 3\nArtifact Registry
floating note #E6E6FA:Services\n\nStep 1\nInstall dependencies\n\nStep 2\nArchive Source\n\nStep 3\nDeployment Manager
-> PubSub\nmessage;
:Cloud Pub/Sub;
-> triggers;
:Cloud Functions;
#DDDDDD:bitbucketBuildUpdate;
#BDB5D5:Notify deployment status;
legend right
    Legend
    | method |
    |<#BDB5D5> process |
    |<#A7C7E7> cloud service |
endlegend
@enduml
