# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
from datetime import date
import os
import sys



# -- Project information -----------------------------------------------------

project = 'rule'
copyright = '2022, UDPlatforms Inc'
author = 'UDPlatforms Inc'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.todo',
    'sphinx.ext.intersphinx'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'

sys.path.append(os.path.abspath('_themes'))
html_theme_path = ['_themes']
html_theme = 'flask'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

master_doc = 'index'

# General information about the project.
project = u'Rakizo Documentation'
copyright = u'{}, Udplatforms Inc.'.format(
    date.today().year)

__namespace = {}
__version_path = os.path.join('..', 'utils', '__version__.py')

if sys.version[0] == '2':
    execfile(__version_path, __namespace)
elif sys.version[0] == '3':
    with open(__version_path, 'rb') as fh:
        __version_contents = fh.read()
    exec(__version_contents, __namespace)
else:
    raise Exception(u'Unsupported version of Python.')

__version__ = __namespace['__version__']
vparts = __version__.split('.')
# The short X.Y version.
version = '.'.join(vparts[:2])
# The full version, including alpha/beta/rc tags.
release = '.'.join(vparts)

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'