@startuml
title Update flow step

#BDB5D5:Client sends a PUT request to /flows/{flow_id}/steps/{step_id};
-> calls;
#ADD1B2:FlowService;
if (update_step) then ({response: flow_step_object}, 200\n yes)
    #ADD1B2:Flow;
    :update_step;
    #ADD1B2:Step;
    :merge;
    #ADD1B2:FlowRepository;
    :save;
    floating note:One of these events will be emitted\nbased on the update:\n\n*StepPositionUpdated\n*StepSizeUpdated\n*StepInfoUpdated
    split
        #ADD1B2:Flow;
    split again
        #ADD1B2:Events/Event;
    end split
    #F2D2BD:Firestore;
    -> triggers;
    #A7C7E7:Publisher;
    kill
else ({'message': 'Flow object not found'}, 404\n no)
    #EB937F:If there is an error, then raise these exceptions:\n*AggregateNotFoundException\n*StepNotFoundException;
    kill
endif
legend right
    Legend
    | method |
    |<#ADD1B2> class |
    |<#EB937F> error |
    |<#F2D2BD> database |
    |<#BDB5D5> process |
    |<#A7C7E7> publisher |
endlegend
@enduml
